### PR TITLE
Make FormatReader sync

### PR DESCRIPTION
**Pull request by sagudev**
similar as https://github.com/pdeljanov/Symphonia/issues/24 just for impl sync trait.

### CODE REVIEW

**Comment by sagudev** [comment]
Had some problems with VSCode formatter which used stable formatter.

The only active nightly formating is `control_brace_style = "ClosingNextLine"`. Is it really needed?

**Comment by sagudev** [comment]
ping @pdeljanov

**Comment by pdeljanov** [comment]
Hi @sagudev,

I'm not 100% up-to-speed on Send/Sync, so I will need to read up and consider the implications of this change and if it'll impose any restrictions to developers. My initial thought is that it should be fine.

That being said, this would be a semver breaking change so I'll make sure to do that before version 0.5 which should be in a couple weeks.

**Comment by pdeljanov** [comment]
Hi  @sagudev,

Thank you for your patience. I think this is a good idea and I see little obvious downside. Would you mind also adding `Sync` to the `codecs::Decoder` and `meta::MetadataReader` traits for consistency and so we can get all the changes in a single commit?

Thanks!

**Comment by sagudev** [comment]
I added Sync to all traits that already implemented Send.

**Comment by pdeljanov** [comment]
Thank you @sagudev!

**Pull request merged**
