### PR TITLE
fix ogg seeking returning an out of bounds error for short files

### LINKED ISSUE #207: SeekError::OutOfRange when seeking to timestamp 0
The following code returns a `SeekError::OutOfRange` with [this audio file](https://github.com/pdeljanov/Symphonia/files/11582986/test.zip):

```rust
use std::{error::Error, fs::File};

use symphonia::core::{
	formats::{FormatOptions, SeekMode, SeekTo},
	io::{MediaSourceStream, MediaSourceStreamOptions},
	meta::MetadataOptions,
	probe::Hint,
};

fn main() -> Result<(), Box<dyn Error>> {
	let probe = symphonia::default::get_probe();
	let mss = MediaSourceStream::new(
		Box::new(File::open("test.ogg")?),
		MediaSourceStreamOptions::default(),
	);
	let mut format_reader = probe
		.format(
			&Hint::default(),
			mss,
			&FormatOptions::default(),
			&MetadataOptions::default(),
		)?
		.format;
	let track = format_reader.default_track().unwrap();
	format_reader.seek(
		SeekMode::Accurate,
		SeekTo::TimeStamp {
			ts: 0,
			track_id: track.id,
		},
	)?;

	Ok(())
}
```

The ogg does have audio, so I don't think this is the correct behavior. I also tried this with mp3, flac, and wav files with the same audio data, and none of them have this issue.

### PR DESCRIPTION
**Pull request by tesselode**
I have no idea if this is the best way to fix it, but it seems to make seeking work correctly for [this test file](https://github.com/pdeljanov/Symphonia/files/11585525/silence.zip) and hasn't broken anything else in my limited testing.

Fixes #207.

### CODE REVIEW

**Comment by pdeljanov** [comment]
Thanks for attempting this!

This part of the seek code is using a binary search to roughly find the OGG page (a group of packets) where the desired packet is. A linear scan follows to find the exact packet.

It seems like the issue occurs because there are no more pages after the seek to the mid-point, so when it tries to find the next page after the seek there are none left.

Therefore, a possible simple solution could just be adding a condition after calculating the mid-point, but before the seek, that breaks out of the binary search:

```rust
if end_byte_pos - start_byte_pos <= 2 * OGG_PAGE_MAX_SIZE as u64 {
    break;
}
```

This same condition is used to terminate the binary search further down as well.

Disclaimer: I haven't really tested this code beyond your broken file, but it makes sense.

**Comment by pdeljanov** [comment]
I'm not sure how familiar you are with the OGG container format, but the [documentation](https://xiph.org/ogg/) is pretty good at explaining the structure of the format.

> Is the point of that condition to check if there's at least 3 pages?

So, the thought process was that after the seek we need to have a page to sync the reader to (after all, we're just seeking to random byte locations in the file). One way to know if there is a page present is if `end - mid >= MAX_PAGE_SIZE`. Since a page can never exceed a maximum size, if the amount of data remaining is larger than that maximum size, there must be a page. That can then be rewritten as `end - start >= 2 * MAX_PAGE_SIZE` since `mid` is halfway between `end` and `start`.

Consider the case where there is only a single page and we seek to `t=0`. Before the seek, the reader is synced to the start of the first page. On seek, `start` is initialized to the byte position of the first byte of the first page, and `end` is initialized to one past the last byte position of the first page. Therefore, `mid` will point to a position in the middle of the first page. If we seek to `mid`, then there are no more pages to sync the reader to and the out-of-range error will be returned. Of course, this is wrong, we just shouldn't have performed that seek because there was no guarantee another page was present. With the change applied, since the condition is not met, the binary search would be immediately halted and the error avoided.

Though, upon further thought, both of these solutions only work if there is only a single logical stream (track) in the file. Multiple logical streams would complicate matters since their pages are interleaved with the track we're seeking.

> Also, how do you recommend testing changes to the decoder? Do you have a suite of audio files you test with?

To be frank, I don't really have many OGG files. The internet archive would be a decent place to find some. @Shnatsel also did a lot of OGG/Vorbis testing back in the day with a decently large corpus.

**Comment by tesselode** [comment]
@pdeljanov regarding multiple tracks, `SeekTo` has a `track_id` field. Would it be reasonable to just try to seek to the timestamp in the specified track, and if the timestamp is out of bounds for that track, then return an `OutOfBounds` error? Or do you mean something else by the pages being interleaved with the tracks and I'm not understanding the issue?

**Comment by pdeljanov** [comment]
Sorry I missed this message.

> @pdeljanov regarding multiple tracks, `SeekTo` has a `track_id` field. Would it be reasonable to just try to seek to the timestamp in the specified track, and if the timestamp is out of bounds for that track, then return an `OutOfBounds` error? 

Yeah, the intention of the `track_id` field is to tell the `FormatReader` to seek that track to the timestamp specified.

> Or do you mean something else by the pages being interleaved with the tracks and I'm not understanding the issue?

I did mean something else however. Basically the issue is the binary search could exclude the last page of a track if the mid-point was within that page (the reader tries to synchronize to the next page which doesn't exist). This resulted in an end-of-stream error.

My suggestion was to only continue the binary search if we know there is at least one page **for the track** between the mid-point and the begin or end (depending which way we're going) boundaries. I suggested calculating the difference between `end` and `start` and comparing it to the maximum possible page size to determine if there must be a page present. This works if there is one track, because if there is a page present, it **must** be for that one track. However, if there are multiple tracks this is not true.

**Comment by pdeljanov** [comment]
Hi @tesselode, thanks for attempting this PR. I'm going to need to close it however since fixing this issue required a more comprehensive change (a1d97f02421de6e29f1dc4ca3c9735073b3bd141).

**Pull request closed without merging**
