### PR TITLE
mention creek in README.md

### PR DESCRIPTION
**Pull request by Be-ing**

### CODE REVIEW

**Comment by Be-ing** [comment]
I opened a [PR for creek](https://github.com/RustyDAW/creek/pull/6) to expose all of Symphonia's Cargo feature flags.

**Comment by pdeljanov** [comment]
Thanks for updating Creek to support newer versions of Symphonia. I'm sure the project will benefit from the increased codec and format support.

That being said, this is an inappropriate pull request.

First, this is basically an advertisement placed in a prominent location in the README.

Second, Symphonia is perfectly safe and can be used as a standalone library as a developer sees fit.

Third, I am aware of, and have been contacted by the authors of, many libraries and projects that use Symphonia as a backend. Each of these projects have their own merits, and I do not wish to endorse any one project over the other.

Please don't make PRs like this.

**Comment by Be-ing** [comment]
> Symphonia is perfectly safe and can be used as a standalone library as a developer sees fit.

Yes, it is, and that's great. Also, I think most developers considering using Symphonia would probably rather use a higher level library that allows them to simply specify a file path and get PCM audio to manipulate in their application or delegate to the library to simply play it for them. Looking at the [dependents on crates.io](https://crates.io/crates/symphonia/reverse_dependencies), there are only 4 crates depending on Symphonia currently:

  * creek: good for realtime audio applications
  * rodio: very high level API suitable for simple applications like a casual music player
  * kira: at a level of abstraction between creek and rodio and adds a few features for manipulating the audio, intended for use in games
  * babycat: a hodgepodge of features that brings in a C dependency... I don't quite get the purpose of this

**Comment by pdeljanov** [comment]
I believe what you are asking for here are more examples. This is a fair critique. Ticket #17 is open if anyone wants to write and submit more examples to the project. Currently, `symphonia-play` is the main working example of using the library. Likewise, `symphonia-check` could also be used as an example as well.

> Looking at the [dependents on crates.io](https://crates.io/crates/symphonia/reverse_dependencies), there are only 4 crates depending on Symphonia currently:
> 
> * creek: good for realtime audio applications
> * rodio: very high level API suitable for simple applications like a casual music player
> * kira: at a level of abstraction between creek and rodio and adds a few features for manipulating the audio, intended for use in games
> * babycat: a hodgepodge of features that brings in a C dependency... I don't quite get the purpose of this

Yes, there are also other applications such as Ruffle, psst, and librespot (currently they're investigating usage) who are using Symphonia with their own audio pipelines that aren't on crates.io.

To be blunt, the main contention against this pull request is that you are trying to promote a project you contribute to in Symphonia's README specifically. Had you added a section towards the *end* of the README with a list of projects and libraries that use Symphonia I would've considered it. But again, this was basically promotion of a specific library.

Let's leave the issue at this.

**Comment by Be-ing** [comment]
An example in the README would be helpful, sure. As someone looking at using this library, I would still appreciate links to other higher level libraries making use of Symphonia, and I think most developers considering the same would probably better off using those higher level libraries than reinventing code that already exists and works well.


Sorry for making a PR that frustrated you. Just for clarity, creek isn't my project; I've just made a few small pull requests to adapt it for [my use case](https://rust-audio.discourse.group/t/a-new-dj-application-in-rust/484) (which will likely result in building an even higher level library on top of creek for variable speed playback).

I hope we can work together on a better note going forward. Thank you very much for this really useful library. I am glad I don't need to bring in a dependency on FFmpeg in a Rust project.

**Comment by pdeljanov** [comment]
Thanks for this. I'm willing to move past this issue as well. As you work on your project, feel free to raise any issues you have and let's see what we can do.

There's no fixed date for the next release, but I'm planning version 0.5 of Symphonia to be a "quality" release (although ALAC, and perhaps even MKV could be included). If you run into any snags or things that don't seem quite right, it can likely be fixed for that release.

**Pull request closed without merging**
